[package]
name = "ratatui-image"
version = "0.3.0"
edition = "2021"
autoexamples = true
authors = ["Benjamin Große <ste3ls@gmail.com>"]
description = "An image widget for ratatui, supporting sixels and unicode-halfblocks"
keywords = ["ratatui", "image", "sixel", "tui", "terminal"]
repository = "https://github.com/benjajaja/ratatui-image"
homepage = "https://github.com/benjajaja/ratatui-image"
readme = "README.md"
license = "MIT"
exclude = [
  "assets/*",
]
rust-version = "1.65.0"

[features]
default = ["sixel", "rustix", "crossterm"]
crossterm = ["dep:crossterm", "ratatui/crossterm"]
termion = ["dep:termion", "ratatui/termion"]
termwiz = ["dep:termwiz", "ratatui/termwiz"]
sixel = ["dep:sixel-bytes"]
serde = ["dep:serde"]
rustix = ["dep:rustix"]

[dependencies]
dyn-clone = "1.0.11"
image = { version = "0.24.5" }
sixel-bytes = { version = "0.2.1", optional = true }
crossterm = { version = "0.25", optional = true }
termion = { version = "2.0", optional = true }
termwiz = { version = "0.20", optional = true }
serde = { version = "^1.0", optional = true, features = ["derive"] }
rustix = { version = "^0.38.4", optional = true, features = ["stdio", "termios"] }
base64 = { version = "^0.21.2" }
rand = { version = "0.8.5" }

[dependencies.ratatui]
version = "0.23.0"
features = []

[[bin]]
name = "ratatui-image"
path = "./src/bin/ratatui-image/main.rs" # cargo readme needs this for some reason
required-features = ["crossterm", "sixel", "rustix"]

[[example]]
name = "demo"
# this runs for all of the terminal backends, so it can't be built using --all-features or scraped
doc-scrape-examples = true

[[example]]
name = "screenshot"
required-features = ["crossterm", "sixel", "rustix"]

# [patch.crates-io]
# ratatui with "cell skipping"
# ratatui = { git = "https://github.com/benjajaja/ratatui", rev = "26fec19e92bcc45eda85cb2b4bc27d4a23833c02" }
